name: "Build apk"
on:
  tag: 
      branches:
        - master
jobs:
  name: "build"
  build:
    run-on: macos-latest
  steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build ios 
      

